### ISSUE TITLE
更新列表（To-do List)

### ISSUE THREAD

**Issue by quank123wip** [Q1mi/Django-REST-framework-documentation#8]
有兴趣参与翻译者，请向dev分支提交
### api-guides部分

- [ ] requests
- [ ] responses
- [ ] views
- [ ] generic-views
- [ ] viewsets
- [ ] routers
- [ ] parsers
- [ ] renderers
- [ ] serializers
- [ ] fields
- [ ] relations
- [ ] validators
- [ ] authentication
- [ ] permissions
- [ ] caching
- [ ] throttling
- [ ] filtering
- [ ] pagination
- [ ] versioning
- [ ] content-negotiation
- [ ] metadata
- [ ] schemas
- [ ] format-suffixes
- [ ] reverse
- [ ] exceptions
- [ ] status-codes
- [ ] testing
- [ ] settings

### community部分

- [ ] 3.0-announcement
- [ ] 3.1-announcement
- [ ] 3.10-announcement
- [ ] 3.11-announcement
- [ ] 3.2-announcement
- [ ] 3.3-announcement
- [ ] 3.4-announcement
- [ ] 3.5-announcement
- [ ] 3.6-announcement
- [ ] 3.7-announcement
- [ ] 3.8-announcement
- [ ] 3.9-announcement
- [ ] contributing
- [ ] funding
- [ ] jobs
- [ ] kickstarter-announcement
- [ ] mozilla-grant
- [ ] project-management
- [ ] release-notes
- [ ] third-party-packages
- [ ] tutorials-and-resources

### tutorial部分

- [ ] 1-serialization
- [ ] 2-requests-and-responses
- [ ] 3-class-based-views
- [ ] 4-authentication-and-permissions
- [ ] 5-relationships-and-hyperlinked-apis
- [ ] 6-viewsets-and-routers
- [ ] quickstart

### topics部分

- [ ] documenting-your-api
- [ ] api-clients
- [ ] internationalization
- [ ] ajax-csrf-cors
- [ ] html-and-forms
- [ ] browser-enhancements
- [ ] browsable-api
- [ ] rest-hypermedia-hateoas

**Comment by CoreJa** [comment]
exceptions部分已提交pr #16
